// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Teams.Invite.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Teams.Invite
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\teams\invite
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InviteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mattermost.Client.api.v4.teams.invite.item collection</summary>
        /// <param name="position">Invite id for a team</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Teams.Invite.Item.WithInvite_ItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Teams.Invite.Item.WithInvite_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("invite_id", position);
                return new global::Mattermost.Client.Api.V4.Teams.Invite.Item.WithInvite_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Teams.Invite.InviteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InviteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/teams/invite", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Teams.Invite.InviteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InviteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/teams/invite", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
