// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Item;
using Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Mention_counts;
using Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Read;
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\{user_id}\teams\{team_id}\threads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThreadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mention_counts property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Mention_counts.Mention_countsRequestBuilder Mention_counts
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Mention_counts.Mention_countsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The read property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Read.ReadRequestBuilder Read
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Read.ReadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Mattermost.Client.api.v4.users.item.teams.item.threads.item collection</summary>
        /// <param name="position">The ID of the thread to follow</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Item.WithThread_ItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Item.WithThread_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("thread_id", position);
                return new global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.Item.WithThread_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThreadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/teams/{team_id}/threads{?deleted*,extended*,page*,per_page*,since*,threadsOnly*,totalsOnly*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThreadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/teams/{team_id}/threads{?deleted*,extended*,page*,per_page*,since*,threadsOnly*,totalsOnly*}", rawUrl)
        {
        }
        /// <summary>
        /// Get all threads that user is following__Minimum server version__: 5.29##### PermissionsMust be logged in as the user or have `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.UserThreads"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.UserThreads?> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder.ThreadsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.UserThreads> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder.ThreadsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.UserThreads>(requestInfo, global::Mattermost.Client.Models.UserThreads.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all threads that user is following__Minimum server version__: 5.29##### PermissionsMust be logged in as the user or have `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder.ThreadsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder.ThreadsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all threads that user is following__Minimum server version__: 5.29##### PermissionsMust be logged in as the user or have `edit_other_users` permission.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ThreadsRequestBuilderGetQueryParameters 
        {
            /// <summary>Deleted will specify that even deleted threads should be returned (For mobile sync).</summary>
            [QueryParameter("deleted")]
            public bool? Deleted { get; set; }
            /// <summary>Extended will enrich the response with participant details.</summary>
            [QueryParameter("extended")]
            public bool? Extended { get; set; }
            /// <summary>Page specifies which part of the results to return, by per_page.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The size of the returned chunk of results.</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Since filters the threads based on their LastUpdateAt timestamp.</summary>
            [QueryParameter("since")]
            public int? Since { get; set; }
            /// <summary>Setting this to true will only return threads.</summary>
            [QueryParameter("threadsOnly")]
            public bool? ThreadsOnly { get; set; }
            /// <summary>Setting this to true will only return the total counts.</summary>
            [QueryParameter("totalsOnly")]
            public bool? TotalsOnly { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ThreadsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Item.Teams.Item.Threads.ThreadsRequestBuilder.ThreadsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
