// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Ldap.Test_diagnostics
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\ldap\test_diagnostics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Test_diagnosticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Test_diagnosticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/ldap/test_diagnostics?test={test}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Test_diagnosticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/ldap/test_diagnostics?test={test}", rawUrl)
        {
        }
        /// <summary>
        /// Test LDAP diagnostics using the provided settings to validate configuration and see sample results without modifying the current server configuration. Use the `test` query parameter to specify which diagnostic to run.##### PermissionsMust have `sysconsole_read_authentication_ldap` or `manage_system` permission.
        /// </summary>
        /// <returns>A List&lt;global::Mattermost.Client.Models.LdapDiagnosticResult&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 500 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Mattermost.Client.Models.LdapDiagnosticResult>?> PostAsync(global::Mattermost.Client.Models.LdapSettings body, Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder.Test_diagnosticsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Mattermost.Client.Models.LdapDiagnosticResult>> PostAsync(global::Mattermost.Client.Models.LdapSettings body, Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder.Test_diagnosticsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "500", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "501", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Mattermost.Client.Models.LdapDiagnosticResult>(requestInfo, global::Mattermost.Client.Models.LdapDiagnosticResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Test LDAP diagnostics using the provided settings to validate configuration and see sample results without modifying the current server configuration. Use the `test` query parameter to specify which diagnostic to run.##### PermissionsMust have `sysconsole_read_authentication_ldap` or `manage_system` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Mattermost.Client.Models.LdapSettings body, Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder.Test_diagnosticsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Mattermost.Client.Models.LdapSettings body, Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder.Test_diagnosticsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Test LDAP diagnostics using the provided settings to validate configuration and see sample results without modifying the current server configuration. Use the `test` query parameter to specify which diagnostic to run.##### PermissionsMust have `sysconsole_read_authentication_ldap` or `manage_system` permission.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Test_diagnosticsRequestBuilderPostQueryParameters 
        {
            /// <summary>Type of LDAP diagnostic test to run</summary>
            [Obsolete("This property is deprecated, use TestAsPostTestQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("test")]
            public string? Test { get; set; }
#nullable restore
#else
            [QueryParameter("test")]
            public string Test { get; set; }
#endif
            /// <summary>Type of LDAP diagnostic test to run</summary>
            [QueryParameter("test")]
            public global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.PostTestQueryParameterType? TestAsPostTestQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Test_diagnosticsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.Ldap.Test_diagnostics.Test_diagnosticsRequestBuilder.Test_diagnosticsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
