// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Mattermost.Client.Plugins.Playbooks.Api.V0.Runs.Item.Checklists.Item.Item_Escaped.Item.State
{
    /// <summary>The new state of the item.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StatePutRequestBody_new_state
    {
        [EnumMember(Value = "in_progress")]
        #pragma warning disable CS1591
        In_progress,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
    }
}
