// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Ldap.Groups.Item.Link;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Ldap.Groups.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\ldap\groups\{remote_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRemote_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The link property</summary>
        public global::Mattermost.Client.Api.V4.Ldap.Groups.Item.Link.LinkRequestBuilder Link
        {
            get => new global::Mattermost.Client.Api.V4.Ldap.Groups.Item.Link.LinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Ldap.Groups.Item.WithRemote_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRemote_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/ldap/groups/{remote_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Ldap.Groups.Item.WithRemote_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRemote_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/ldap/groups/{remote_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
