// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Api.V4.Teams.Item.Posts.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Set to true if deleted channels should be included in the search. (archived channels)</summary>
        public bool? IncludeDeletedChannels { get; set; }
        /// <summary>Set to true if an Or search should be performed vs an And search.</summary>
        public bool? IsOrSearch { get; set; }
        /// <summary>The page to select. (Only works with Elasticsearch)</summary>
        public int? Page { get; set; }
        /// <summary>The number of posts per page. (Only works with Elasticsearch)</summary>
        public int? PerPage { get; set; }
        /// <summary>The search terms as inputed by the user. To search for posts from a user include `from:someusername`, using a user&apos;s username. To search in a specific channel include `in:somechannel`, using the channel name (not the display name).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Terms { get; set; }
#nullable restore
#else
        public string Terms { get; set; }
#endif
        /// <summary>Offset from UTC of user timezone for date searches.</summary>
        public int? TimeZoneOffset { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Teams.Item.Posts.Search.SearchPostRequestBody"/> and sets the default values.
        /// </summary>
        public SearchPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Teams.Item.Posts.Search.SearchPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Api.V4.Teams.Item.Posts.Search.SearchPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Api.V4.Teams.Item.Posts.Search.SearchPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "include_deleted_channels", n => { IncludeDeletedChannels = n.GetBoolValue(); } },
                { "is_or_search", n => { IsOrSearch = n.GetBoolValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "per_page", n => { PerPage = n.GetIntValue(); } },
                { "terms", n => { Terms = n.GetStringValue(); } },
                { "time_zone_offset", n => { TimeZoneOffset = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("include_deleted_channels", IncludeDeletedChannels);
            writer.WriteBoolValue("is_or_search", IsOrSearch);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("per_page", PerPage);
            writer.WriteStringValue("terms", Terms);
            writer.WriteIntValue("time_zone_offset", TimeZoneOffset);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
