// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Item.Active;
using Mattermost.Client.Api.V4.Users.Item.Audits;
using Mattermost.Client.Api.V4.Users.Item.Auth;
using Mattermost.Client.Api.V4.Users.Item.Channel_members;
using Mattermost.Client.Api.V4.Users.Item.Channels;
using Mattermost.Client.Api.V4.Users.Item.Convert_to_bot;
using Mattermost.Client.Api.V4.Users.Item.Custom_profile_attributes;
using Mattermost.Client.Api.V4.Users.Item.Data_retention;
using Mattermost.Client.Api.V4.Users.Item.Demote;
using Mattermost.Client.Api.V4.Users.Item.Email;
using Mattermost.Client.Api.V4.Users.Item.Groups;
using Mattermost.Client.Api.V4.Users.Item.Image;
using Mattermost.Client.Api.V4.Users.Item.Mfa;
using Mattermost.Client.Api.V4.Users.Item.Oauth;
using Mattermost.Client.Api.V4.Users.Item.Password;
using Mattermost.Client.Api.V4.Users.Item.Patch;
using Mattermost.Client.Api.V4.Users.Item.Posts;
using Mattermost.Client.Api.V4.Users.Item.Preferences;
using Mattermost.Client.Api.V4.Users.Item.Promote;
using Mattermost.Client.Api.V4.Users.Item.Reset_failed_attempts;
using Mattermost.Client.Api.V4.Users.Item.Roles;
using Mattermost.Client.Api.V4.Users.Item.Sessions;
using Mattermost.Client.Api.V4.Users.Item.Status;
using Mattermost.Client.Api.V4.Users.Item.Teams;
using Mattermost.Client.Api.V4.Users.Item.Terms_of_service;
using Mattermost.Client.Api.V4.Users.Item.Tokens;
using Mattermost.Client.Api.V4.Users.Item.Typing;
using Mattermost.Client.Api.V4.Users.Item.Uploads;
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\{user_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUser_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Active.ActiveRequestBuilder Active
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audits property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Audits.AuditsRequestBuilder Audits
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Audits.AuditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Auth.AuthRequestBuilder Auth
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The channel_members property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Channel_members.Channel_membersRequestBuilder Channel_members
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Channel_members.Channel_membersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The channels property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The convert_to_bot property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Convert_to_bot.Convert_to_botRequestBuilder Convert_to_bot
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Convert_to_bot.Convert_to_botRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_profile_attributes property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Custom_profile_attributes.Custom_profile_attributesRequestBuilder Custom_profile_attributes
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Custom_profile_attributes.Custom_profile_attributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The data_retention property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Data_retention.Data_retentionRequestBuilder Data_retention
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Data_retention.Data_retentionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The demote property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Demote.DemoteRequestBuilder Demote
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Demote.DemoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Email.EmailRequestBuilder Email
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Groups.GroupsRequestBuilder Groups
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Image.ImageRequestBuilder Image
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mfa property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Mfa.MfaRequestBuilder Mfa
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Mfa.MfaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The password property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Password.PasswordRequestBuilder Password
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patchPath property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Patch.PatchRequestBuilder PatchPath
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Patch.PatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Posts.PostsRequestBuilder Posts
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The preferences property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Preferences.PreferencesRequestBuilder Preferences
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Preferences.PreferencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The promote property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Promote.PromoteRequestBuilder Promote
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Promote.PromoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset_failed_attempts property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Reset_failed_attempts.Reset_failed_attemptsRequestBuilder Reset_failed_attempts
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Reset_failed_attempts.Reset_failed_attemptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Roles.RolesRequestBuilder Roles
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Status.StatusRequestBuilder Status
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terms_of_service property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Terms_of_service.Terms_of_serviceRequestBuilder Terms_of_service
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Terms_of_service.Terms_of_serviceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokens property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Tokens.TokensRequestBuilder Tokens
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Tokens.TokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The typing property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Typing.TypingRequestBuilder Typing
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Typing.TypingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploads property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Uploads.UploadsRequestBuilder Uploads
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Uploads.UploadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.WithUser_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.WithUser_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUser_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}", rawUrl)
        {
        }
        /// <summary>
        /// Deactivates the user and revokes all its sessions by archiving its user object.As of server version 5.28, optionally use the `permanent=true` query parameter to permanently delete the user for compliance reasons. To use this feature `ServiceSettings.EnableAPIUserDeletion` must be set to `true` in the server&apos;s configuration.##### PermissionsMust be logged in as the user being deactivated or have the `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.StatusOK"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.StatusOK?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.StatusOK> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.StatusOK>(requestInfo, global::Mattermost.Client.Models.StatusOK.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a user a object. Sensitive information will be sanitized out.##### PermissionsRequires an active session but no other permissions.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.User"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.User?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.User> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.User>(requestInfo, global::Mattermost.Client.Models.User.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a user by providing the user object. The fields that can be updated are defined in the request body, all other provided fields will be ignored. Any fields not included in the request body will be set to null or reverted to default values.##### PermissionsMust be logged in as the user being updated or have the `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.User"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.User?> PutAsync(global::Mattermost.Client.Api.V4.Users.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.User> PutAsync(global::Mattermost.Client.Api.V4.Users.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.User>(requestInfo, global::Mattermost.Client.Models.User.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deactivates the user and revokes all its sessions by archiving its user object.As of server version 5.28, optionally use the `permanent=true` query parameter to permanently delete the user for compliance reasons. To use this feature `ServiceSettings.EnableAPIUserDeletion` must be set to `true` in the server&apos;s configuration.##### PermissionsMust be logged in as the user being deactivated or have the `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get a user a object. Sensitive information will be sanitized out.##### PermissionsRequires an active session but no other permissions.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a user by providing the user object. The fields that can be updated are defined in the request body, all other provided fields will be ignored. Any fields not included in the request body will be set to null or reverted to default values.##### PermissionsMust be logged in as the user being updated or have the `edit_other_users` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Mattermost.Client.Api.V4.Users.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Mattermost.Client.Api.V4.Users.Item.WithUser_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Item.WithUser_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Users.Item.WithUser_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Users.Item.WithUser_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUser_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUser_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithUser_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
