// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Item.Channels.Item.Posts;
using Mattermost.Client.Api.V4.Users.Item.Channels.Item.Unread;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Users.Item.Channels.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\{user_id}\channels\{channel_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithChannel_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The posts property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.Posts.PostsRequestBuilder Posts
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unread property</summary>
        public global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.Unread.UnreadRequestBuilder Unread
        {
            get => new global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.Unread.UnreadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.WithChannel_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithChannel_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/channels/{channel_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Channels.Item.WithChannel_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithChannel_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/channels/{channel_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
