// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Api.V4.Channels.Members.Item.View
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ViewPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A JSON object mapping channel IDs to the channel view times</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse_last_viewed_at_times? LastViewedAtTimes { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse_last_viewed_at_times LastViewedAtTimes { get; set; }
#endif
        /// <summary>Value should be &quot;OK&quot; if successful</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse"/> and sets the default values.
        /// </summary>
        public ViewPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "last_viewed_at_times", n => { LastViewedAtTimes = n.GetObjectValue<global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse_last_viewed_at_times>(global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse_last_viewed_at_times.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Mattermost.Client.Api.V4.Channels.Members.Item.View.ViewPostResponse_last_viewed_at_times>("last_viewed_at_times", LastViewedAtTimes);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
