// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Groups.Item.Restore
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\groups\{group_id}\restore
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RestoreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Groups.Item.Restore.RestoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestoreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{group_id}/restore", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Groups.Item.Restore.RestoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RestoreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/groups/{group_id}/restore", rawUrl)
        {
        }
        /// <summary>
        /// Restores a previously deleted custom group, allowing it to be used normally.May not be used with LDAP groups.##### Permissions Must have `restore_custom_group` permission for the given group.__Minimum server version__: 7.7
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.StatusOK"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.StatusOK?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.StatusOK> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "501", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.StatusOK>(requestInfo, global::Mattermost.Client.Models.StatusOK.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Restores a previously deleted custom group, allowing it to be used normally.May not be used with LDAP groups.##### Permissions Must have `restore_custom_group` permission for the given group.__Minimum server version__: 7.7
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Groups.Item.Restore.RestoreRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Groups.Item.Restore.RestoreRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Groups.Item.Restore.RestoreRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RestoreRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
