// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Access_control_policies;
using Mattermost.Client.Api.V4.Actions;
using Mattermost.Client.Api.V4.Analytics;
using Mattermost.Client.Api.V4.Audit_logs;
using Mattermost.Client.Api.V4.Audits;
using Mattermost.Client.Api.V4.Bleve;
using Mattermost.Client.Api.V4.Bots;
using Mattermost.Client.Api.V4.Brand;
using Mattermost.Client.Api.V4.Caches;
using Mattermost.Client.Api.V4.Channels;
using Mattermost.Client.Api.V4.Client_perf;
using Mattermost.Client.Api.V4.Cloud;
using Mattermost.Client.Api.V4.Cluster;
using Mattermost.Client.Api.V4.Commands;
using Mattermost.Client.Api.V4.Compliance;
using Mattermost.Client.Api.V4.Config;
using Mattermost.Client.Api.V4.Custom_profile_attributes;
using Mattermost.Client.Api.V4.Data_retention;
using Mattermost.Client.Api.V4.Database;
using Mattermost.Client.Api.V4.Elasticsearch;
using Mattermost.Client.Api.V4.Email;
using Mattermost.Client.Api.V4.Emoji;
using Mattermost.Client.Api.V4.Exports;
using Mattermost.Client.Api.V4.FileNamespace;
using Mattermost.Client.Api.V4.Files;
using Mattermost.Client.Api.V4.Groups;
using Mattermost.Client.Api.V4.Hooks;
using Mattermost.Client.Api.V4.Image;
using Mattermost.Client.Api.V4.Imports;
using Mattermost.Client.Api.V4.Integrity;
using Mattermost.Client.Api.V4.Ip_filtering;
using Mattermost.Client.Api.V4.Jobs;
using Mattermost.Client.Api.V4.Ldap;
using Mattermost.Client.Api.V4.License;
using Mattermost.Client.Api.V4.Limits;
using Mattermost.Client.Api.V4.Logs;
using Mattermost.Client.Api.V4.Notifications;
using Mattermost.Client.Api.V4.Oauth;
using Mattermost.Client.Api.V4.Permissions;
using Mattermost.Client.Api.V4.Plugins;
using Mattermost.Client.Api.V4.Posts;
using Mattermost.Client.Api.V4.Reactions;
using Mattermost.Client.Api.V4.Redirect_location;
using Mattermost.Client.Api.V4.Remotecluster;
using Mattermost.Client.Api.V4.Reports;
using Mattermost.Client.Api.V4.Restart;
using Mattermost.Client.Api.V4.Roles;
using Mattermost.Client.Api.V4.Saml;
using Mattermost.Client.Api.V4.Schemes;
using Mattermost.Client.Api.V4.Server_busy;
using Mattermost.Client.Api.V4.Sharedchannels;
using Mattermost.Client.Api.V4.Site_url;
using Mattermost.Client.Api.V4.System;
using Mattermost.Client.Api.V4.Teams;
using Mattermost.Client.Api.V4.Terms_of_service;
using Mattermost.Client.Api.V4.TrialLicense;
using Mattermost.Client.Api.V4.Upgrade_to_enterprise;
using Mattermost.Client.Api.V4.Uploads;
using Mattermost.Client.Api.V4.Usage;
using Mattermost.Client.Api.V4.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V4RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The access_control_policies property</summary>
        public global::Mattermost.Client.Api.V4.Access_control_policies.Access_control_policiesRequestBuilder Access_control_policies
        {
            get => new global::Mattermost.Client.Api.V4.Access_control_policies.Access_control_policiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The actions property</summary>
        public global::Mattermost.Client.Api.V4.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Mattermost.Client.Api.V4.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The analytics property</summary>
        public global::Mattermost.Client.Api.V4.Analytics.AnalyticsRequestBuilder Analytics
        {
            get => new global::Mattermost.Client.Api.V4.Analytics.AnalyticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audit_logs property</summary>
        public global::Mattermost.Client.Api.V4.Audit_logs.Audit_logsRequestBuilder Audit_logs
        {
            get => new global::Mattermost.Client.Api.V4.Audit_logs.Audit_logsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audits property</summary>
        public global::Mattermost.Client.Api.V4.Audits.AuditsRequestBuilder Audits
        {
            get => new global::Mattermost.Client.Api.V4.Audits.AuditsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bleve property</summary>
        public global::Mattermost.Client.Api.V4.Bleve.BleveRequestBuilder Bleve
        {
            get => new global::Mattermost.Client.Api.V4.Bleve.BleveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bots property</summary>
        public global::Mattermost.Client.Api.V4.Bots.BotsRequestBuilder Bots
        {
            get => new global::Mattermost.Client.Api.V4.Bots.BotsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The brand property</summary>
        public global::Mattermost.Client.Api.V4.Brand.BrandRequestBuilder Brand
        {
            get => new global::Mattermost.Client.Api.V4.Brand.BrandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The caches property</summary>
        public global::Mattermost.Client.Api.V4.Caches.CachesRequestBuilder Caches
        {
            get => new global::Mattermost.Client.Api.V4.Caches.CachesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The channels property</summary>
        public global::Mattermost.Client.Api.V4.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Mattermost.Client.Api.V4.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The client_perf property</summary>
        public global::Mattermost.Client.Api.V4.Client_perf.Client_perfRequestBuilder Client_perf
        {
            get => new global::Mattermost.Client.Api.V4.Client_perf.Client_perfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cloud property</summary>
        public global::Mattermost.Client.Api.V4.Cloud.CloudRequestBuilder Cloud
        {
            get => new global::Mattermost.Client.Api.V4.Cloud.CloudRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cluster property</summary>
        public global::Mattermost.Client.Api.V4.Cluster.ClusterRequestBuilder Cluster
        {
            get => new global::Mattermost.Client.Api.V4.Cluster.ClusterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The commands property</summary>
        public global::Mattermost.Client.Api.V4.Commands.CommandsRequestBuilder Commands
        {
            get => new global::Mattermost.Client.Api.V4.Commands.CommandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compliance property</summary>
        public global::Mattermost.Client.Api.V4.Compliance.ComplianceRequestBuilder Compliance
        {
            get => new global::Mattermost.Client.Api.V4.Compliance.ComplianceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::Mattermost.Client.Api.V4.Config.ConfigRequestBuilder Config
        {
            get => new global::Mattermost.Client.Api.V4.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_profile_attributes property</summary>
        public global::Mattermost.Client.Api.V4.Custom_profile_attributes.Custom_profile_attributesRequestBuilder Custom_profile_attributes
        {
            get => new global::Mattermost.Client.Api.V4.Custom_profile_attributes.Custom_profile_attributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The data_retention property</summary>
        public global::Mattermost.Client.Api.V4.Data_retention.Data_retentionRequestBuilder Data_retention
        {
            get => new global::Mattermost.Client.Api.V4.Data_retention.Data_retentionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The database property</summary>
        public global::Mattermost.Client.Api.V4.Database.DatabaseRequestBuilder Database
        {
            get => new global::Mattermost.Client.Api.V4.Database.DatabaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The elasticsearch property</summary>
        public global::Mattermost.Client.Api.V4.Elasticsearch.ElasticsearchRequestBuilder Elasticsearch
        {
            get => new global::Mattermost.Client.Api.V4.Elasticsearch.ElasticsearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Mattermost.Client.Api.V4.Email.EmailRequestBuilder Email
        {
            get => new global::Mattermost.Client.Api.V4.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emoji property</summary>
        public global::Mattermost.Client.Api.V4.Emoji.EmojiRequestBuilder Emoji
        {
            get => new global::Mattermost.Client.Api.V4.Emoji.EmojiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exports property</summary>
        public global::Mattermost.Client.Api.V4.Exports.ExportsRequestBuilder Exports
        {
            get => new global::Mattermost.Client.Api.V4.Exports.ExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The file property</summary>
        public global::Mattermost.Client.Api.V4.FileNamespace.FileRequestBuilder File
        {
            get => new global::Mattermost.Client.Api.V4.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Mattermost.Client.Api.V4.Files.FilesRequestBuilder Files
        {
            get => new global::Mattermost.Client.Api.V4.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::Mattermost.Client.Api.V4.Groups.GroupsRequestBuilder Groups
        {
            get => new global::Mattermost.Client.Api.V4.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hooks property</summary>
        public global::Mattermost.Client.Api.V4.Hooks.HooksRequestBuilder Hooks
        {
            get => new global::Mattermost.Client.Api.V4.Hooks.HooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image property</summary>
        public global::Mattermost.Client.Api.V4.Image.ImageRequestBuilder Image
        {
            get => new global::Mattermost.Client.Api.V4.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The imports property</summary>
        public global::Mattermost.Client.Api.V4.Imports.ImportsRequestBuilder Imports
        {
            get => new global::Mattermost.Client.Api.V4.Imports.ImportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrity property</summary>
        public global::Mattermost.Client.Api.V4.Integrity.IntegrityRequestBuilder Integrity
        {
            get => new global::Mattermost.Client.Api.V4.Integrity.IntegrityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ip_filtering property</summary>
        public global::Mattermost.Client.Api.V4.Ip_filtering.Ip_filteringRequestBuilder Ip_filtering
        {
            get => new global::Mattermost.Client.Api.V4.Ip_filtering.Ip_filteringRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Mattermost.Client.Api.V4.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Mattermost.Client.Api.V4.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ldap property</summary>
        public global::Mattermost.Client.Api.V4.Ldap.LdapRequestBuilder Ldap
        {
            get => new global::Mattermost.Client.Api.V4.Ldap.LdapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The license property</summary>
        public global::Mattermost.Client.Api.V4.License.LicenseRequestBuilder License
        {
            get => new global::Mattermost.Client.Api.V4.License.LicenseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The limits property</summary>
        public global::Mattermost.Client.Api.V4.Limits.LimitsRequestBuilder Limits
        {
            get => new global::Mattermost.Client.Api.V4.Limits.LimitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logs property</summary>
        public global::Mattermost.Client.Api.V4.Logs.LogsRequestBuilder Logs
        {
            get => new global::Mattermost.Client.Api.V4.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Mattermost.Client.Api.V4.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Mattermost.Client.Api.V4.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Mattermost.Client.Api.V4.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Mattermost.Client.Api.V4.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::Mattermost.Client.Api.V4.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::Mattermost.Client.Api.V4.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::Mattermost.Client.Api.V4.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::Mattermost.Client.Api.V4.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posts property</summary>
        public global::Mattermost.Client.Api.V4.Posts.PostsRequestBuilder Posts
        {
            get => new global::Mattermost.Client.Api.V4.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reactions property</summary>
        public global::Mattermost.Client.Api.V4.Reactions.ReactionsRequestBuilder Reactions
        {
            get => new global::Mattermost.Client.Api.V4.Reactions.ReactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redirect_location property</summary>
        public global::Mattermost.Client.Api.V4.Redirect_location.Redirect_locationRequestBuilder Redirect_location
        {
            get => new global::Mattermost.Client.Api.V4.Redirect_location.Redirect_locationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The remotecluster property</summary>
        public global::Mattermost.Client.Api.V4.Remotecluster.RemoteclusterRequestBuilder Remotecluster
        {
            get => new global::Mattermost.Client.Api.V4.Remotecluster.RemoteclusterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reports property</summary>
        public global::Mattermost.Client.Api.V4.Reports.ReportsRequestBuilder Reports
        {
            get => new global::Mattermost.Client.Api.V4.Reports.ReportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restart property</summary>
        public global::Mattermost.Client.Api.V4.Restart.RestartRequestBuilder Restart
        {
            get => new global::Mattermost.Client.Api.V4.Restart.RestartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Mattermost.Client.Api.V4.Roles.RolesRequestBuilder Roles
        {
            get => new global::Mattermost.Client.Api.V4.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saml property</summary>
        public global::Mattermost.Client.Api.V4.Saml.SamlRequestBuilder Saml
        {
            get => new global::Mattermost.Client.Api.V4.Saml.SamlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schemes property</summary>
        public global::Mattermost.Client.Api.V4.Schemes.SchemesRequestBuilder Schemes
        {
            get => new global::Mattermost.Client.Api.V4.Schemes.SchemesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The server_busy property</summary>
        public global::Mattermost.Client.Api.V4.Server_busy.Server_busyRequestBuilder Server_busy
        {
            get => new global::Mattermost.Client.Api.V4.Server_busy.Server_busyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sharedchannels property</summary>
        public global::Mattermost.Client.Api.V4.Sharedchannels.SharedchannelsRequestBuilder Sharedchannels
        {
            get => new global::Mattermost.Client.Api.V4.Sharedchannels.SharedchannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The site_url property</summary>
        public global::Mattermost.Client.Api.V4.Site_url.Site_urlRequestBuilder Site_url
        {
            get => new global::Mattermost.Client.Api.V4.Site_url.Site_urlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The system property</summary>
        public global::Mattermost.Client.Api.V4.System.SystemRequestBuilder System
        {
            get => new global::Mattermost.Client.Api.V4.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Mattermost.Client.Api.V4.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Mattermost.Client.Api.V4.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terms_of_service property</summary>
        public global::Mattermost.Client.Api.V4.Terms_of_service.Terms_of_serviceRequestBuilder Terms_of_service
        {
            get => new global::Mattermost.Client.Api.V4.Terms_of_service.Terms_of_serviceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trialLicense property</summary>
        public global::Mattermost.Client.Api.V4.TrialLicense.TrialLicenseRequestBuilder TrialLicense
        {
            get => new global::Mattermost.Client.Api.V4.TrialLicense.TrialLicenseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upgrade_to_enterprise property</summary>
        public global::Mattermost.Client.Api.V4.Upgrade_to_enterprise.Upgrade_to_enterpriseRequestBuilder Upgrade_to_enterprise
        {
            get => new global::Mattermost.Client.Api.V4.Upgrade_to_enterprise.Upgrade_to_enterpriseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploads property</summary>
        public global::Mattermost.Client.Api.V4.Uploads.UploadsRequestBuilder Uploads
        {
            get => new global::Mattermost.Client.Api.V4.Uploads.UploadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::Mattermost.Client.Api.V4.Usage.UsageRequestBuilder Usage
        {
            get => new global::Mattermost.Client.Api.V4.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Mattermost.Client.Api.V4.Users.UsersRequestBuilder Users
        {
            get => new global::Mattermost.Client.Api.V4.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.V4RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V4RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.V4RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V4RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
