// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\{user_id}\preferences\{category}\name
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NameRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mattermost.Client.api.v4.users.item.preferences.item.name.item collection</summary>
        /// <param name="position">The name of the preference</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.Item.WithPreference_nameItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.Item.WithPreference_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("preference_name", position);
                return new global::Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.Item.WithPreference_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.NameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/preferences/{category}/name", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Preferences.Item.Name.NameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/preferences/{category}/name", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
