// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Teams.Invites.Email;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Teams.Invites
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\teams\invites
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvitesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The email property</summary>
        public global::Mattermost.Client.Api.V4.Teams.Invites.Email.EmailRequestBuilder Email
        {
            get => new global::Mattermost.Client.Api.V4.Teams.Invites.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Teams.Invites.InvitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvitesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/teams/invites", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Teams.Invites.InvitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvitesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/teams/invites", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
