// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Username.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Users.Username
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\username
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsernameRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mattermost.Client.api.v4.users.username.item collection</summary>
        /// <param name="position">Username</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Username.Item.WithUsernameItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Users.Username.Item.WithUsernameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("username", position);
                return new global::Mattermost.Client.Api.V4.Users.Username.Item.WithUsernameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Username.UsernameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsernameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/username", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Username.UsernameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsernameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/username", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
