// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Schemes.Item.Channels;
using Mattermost.Client.Api.V4.Schemes.Item.Patch;
using Mattermost.Client.Api.V4.Schemes.Item.Teams;
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Schemes.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\schemes\{scheme_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithScheme_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The channels property</summary>
        public global::Mattermost.Client.Api.V4.Schemes.Item.Channels.ChannelsRequestBuilder Channels
        {
            get => new global::Mattermost.Client.Api.V4.Schemes.Item.Channels.ChannelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patchPath property</summary>
        public global::Mattermost.Client.Api.V4.Schemes.Item.Patch.PatchRequestBuilder PatchPath
        {
            get => new global::Mattermost.Client.Api.V4.Schemes.Item.Patch.PatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Mattermost.Client.Api.V4.Schemes.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Mattermost.Client.Api.V4.Schemes.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Schemes.Item.WithScheme_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithScheme_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/schemes/{scheme_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Schemes.Item.WithScheme_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithScheme_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/schemes/{scheme_id}", rawUrl)
        {
        }
        /// <summary>
        /// Soft deletes a scheme, by marking the scheme as deleted in the database.##### PermissionsMust have `manage_system` permission.__Minimum server version__: 5.0
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.StatusOK"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.StatusOK?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.StatusOK> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "501", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.StatusOK>(requestInfo, global::Mattermost.Client.Models.StatusOK.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a scheme from the provided scheme id.##### PermissionsMust have `manage_system` permission.__Minimum server version__: 5.0
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Scheme"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.Scheme?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.Scheme> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "501", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.Scheme>(requestInfo, global::Mattermost.Client.Models.Scheme.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Soft deletes a scheme, by marking the scheme as deleted in the database.##### PermissionsMust have `manage_system` permission.__Minimum server version__: 5.0
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get a scheme from the provided scheme id.##### PermissionsMust have `manage_system` permission.__Minimum server version__: 5.0
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Schemes.Item.WithScheme_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Schemes.Item.WithScheme_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Schemes.Item.WithScheme_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithScheme_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithScheme_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
