// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Mattermost.Client.Api.V4.Custom_profile_attributes.Fields
{
    /// <summary>Type of text value</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FieldsPostRequestBody_attrs_value_type
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
    }
}
