// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Users.Stats.Filtered
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\stats\filtered
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilteredRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilteredRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/stats/filtered{?channel_roles*,in_channel*,in_team*,include_bots*,include_deleted*,roles*,team_roles*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilteredRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/stats/filtered{?channel_roles*,in_channel*,in_team*,include_bots*,include_deleted*,roles*,team_roles*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a count of users in the system matching the specified filters.__Minimum server version__: 5.26##### PermissionsMust have `manage_system` permission.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.UsersStats"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.UsersStats?> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder.FilteredRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.UsersStats> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder.FilteredRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.UsersStats>(requestInfo, global::Mattermost.Client.Models.UsersStats.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a count of users in the system matching the specified filters.__Minimum server version__: 5.26##### PermissionsMust have `manage_system` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder.FilteredRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder.FilteredRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a count of users in the system matching the specified filters.__Minimum server version__: 5.26##### PermissionsMust have `manage_system` permission.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilteredRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma separated string used to filter users based on any of the specified channel roles, can only be used in conjunction with `in_channel`Example: `?in_channel=4eb6axxw7fg3je5iyasnfudc5y&amp;channel_roles=channel_user` will include users that are only channel users and not admins or guests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("channel_roles")]
            public string? ChannelRoles { get; set; }
#nullable restore
#else
            [QueryParameter("channel_roles")]
            public string ChannelRoles { get; set; }
#endif
            /// <summary>The ID of the channel to get user stats for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("in_channel")]
            public string? InChannel { get; set; }
#nullable restore
#else
            [QueryParameter("in_channel")]
            public string InChannel { get; set; }
#endif
            /// <summary>If bot accounts should be included in the count.</summary>
            [QueryParameter("include_bots")]
            public bool? IncludeBots { get; set; }
            /// <summary>If deleted accounts should be included in the count.</summary>
            [QueryParameter("include_deleted")]
            public bool? IncludeDeleted { get; set; }
            /// <summary>The ID of the team to get user stats for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("in_team")]
            public string? InTeam { get; set; }
#nullable restore
#else
            [QueryParameter("in_team")]
            public string InTeam { get; set; }
#endif
            /// <summary>Comma separated string used to filter users based on any of the specified system rolesExample: `?roles=system_admin,system_user` will include users that are either system admins or system users</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("roles")]
            public string? Roles { get; set; }
#nullable restore
#else
            [QueryParameter("roles")]
            public string Roles { get; set; }
#endif
            /// <summary>Comma separated string used to filter users based on any of the specified team roles, can only be used in conjunction with `in_team`Example: `?in_team=4eb6axxw7fg3je5iyasnfudc5y&amp;team_roles=team_user` will include users that are only team users and not admins or guests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team_roles")]
            public string? TeamRoles { get; set; }
#nullable restore
#else
            [QueryParameter("team_roles")]
            public string TeamRoles { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FilteredRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Stats.Filtered.FilteredRequestBuilder.FilteredRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
