// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Migrate_auth.Ldap;
using Mattermost.Client.Api.V4.Users.Migrate_auth.Saml;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Users.Migrate_auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\migrate_auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Migrate_authRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ldap property</summary>
        public global::Mattermost.Client.Api.V4.Users.Migrate_auth.Ldap.LdapRequestBuilder Ldap
        {
            get => new global::Mattermost.Client.Api.V4.Users.Migrate_auth.Ldap.LdapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The saml property</summary>
        public global::Mattermost.Client.Api.V4.Users.Migrate_auth.Saml.SamlRequestBuilder Saml
        {
            get => new global::Mattermost.Client.Api.V4.Users.Migrate_auth.Saml.SamlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Migrate_auth.Migrate_authRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Migrate_authRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/migrate_auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Migrate_auth.Migrate_authRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Migrate_authRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/migrate_auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
