// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Saml.Certificate.Idp;
using Mattermost.Client.Api.V4.Saml.Certificate.Private;
using Mattermost.Client.Api.V4.Saml.Certificate.Public;
using Mattermost.Client.Api.V4.Saml.Certificate.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Saml.Certificate
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\saml\certificate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CertificateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The idp property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Certificate.Idp.IdpRequestBuilder Idp
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Certificate.Idp.IdpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The private property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Certificate.Private.PrivateRequestBuilder Private
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Certificate.Private.PrivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The public property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Certificate.Public.PublicRequestBuilder Public
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Certificate.Public.PublicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Certificate.Status.StatusRequestBuilder Status
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Certificate.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Saml.Certificate.CertificateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/saml/certificate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Saml.Certificate.CertificateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/saml/certificate", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
