// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Tokens.Disable;
using Mattermost.Client.Api.V4.Users.Tokens.Enable;
using Mattermost.Client.Api.V4.Users.Tokens.Item;
using Mattermost.Client.Api.V4.Users.Tokens.Revoke;
using Mattermost.Client.Api.V4.Users.Tokens.Search;
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Users.Tokens
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\tokens
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokensRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The disable property</summary>
        public global::Mattermost.Client.Api.V4.Users.Tokens.Disable.DisableRequestBuilder Disable
        {
            get => new global::Mattermost.Client.Api.V4.Users.Tokens.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::Mattermost.Client.Api.V4.Users.Tokens.Enable.EnableRequestBuilder Enable
        {
            get => new global::Mattermost.Client.Api.V4.Users.Tokens.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The revoke property</summary>
        public global::Mattermost.Client.Api.V4.Users.Tokens.Revoke.RevokeRequestBuilder Revoke
        {
            get => new global::Mattermost.Client.Api.V4.Users.Tokens.Revoke.RevokeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Mattermost.Client.Api.V4.Users.Tokens.Search.SearchRequestBuilder Search
        {
            get => new global::Mattermost.Client.Api.V4.Users.Tokens.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Mattermost.Client.api.v4.users.tokens.item collection</summary>
        /// <param name="position">User access token GUID</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Tokens.Item.WithToken_ItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Users.Tokens.Item.WithToken_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("token_id", position);
                return new global::Mattermost.Client.Api.V4.Users.Tokens.Item.WithToken_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokensRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/tokens{?page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokensRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/tokens{?page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a page of user access tokens for users on the system. Does not include the actual authentication tokens. Use query parameters for paging.__Minimum server version__: 4.7##### PermissionsMust have `manage_system` permission.
        /// </summary>
        /// <returns>A List&lt;global::Mattermost.Client.Models.UserAccessTokenSanitized&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Mattermost.Client.Models.UserAccessTokenSanitized>?> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder.TokensRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Mattermost.Client.Models.UserAccessTokenSanitized>> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder.TokensRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Mattermost.Client.Models.UserAccessTokenSanitized>(requestInfo, global::Mattermost.Client.Models.UserAccessTokenSanitized.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Get a page of user access tokens for users on the system. Does not include the actual authentication tokens. Use query parameters for paging.__Minimum server version__: 4.7##### PermissionsMust have `manage_system` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder.TokensRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder.TokensRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a page of user access tokens for users on the system. Does not include the actual authentication tokens. Use query parameters for paging.__Minimum server version__: 4.7##### PermissionsMust have `manage_system` permission.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TokensRequestBuilderGetQueryParameters 
        {
            /// <summary>The page to select.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of tokens per page.</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TokensRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.Users.Tokens.TokensRequestBuilder.TokensRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
