// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Channel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time in milliseconds a channel was created</summary>
        public long? CreateAt { get; set; }
        /// <summary>The creator_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The time in milliseconds a channel was deleted</summary>
        public long? DeleteAt { get; set; }
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Deprecated in Mattermost 5.0 release</summary>
        public long? ExtraUpdateAt { get; set; }
        /// <summary>The header property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Header { get; set; }
#nullable restore
#else
        public string Header { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The time in milliseconds of the last post of a channel</summary>
        public long? LastPostAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The purpose property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Purpose { get; set; }
#nullable restore
#else
        public string Purpose { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The total_msg_count property</summary>
        public int? TotalMsgCount { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The time in milliseconds a channel was last updated</summary>
        public long? UpdateAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.Channel"/> and sets the default values.
        /// </summary>
        public Channel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Channel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.Channel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.Channel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "create_at", n => { CreateAt = n.GetLongValue(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "delete_at", n => { DeleteAt = n.GetLongValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "extra_update_at", n => { ExtraUpdateAt = n.GetLongValue(); } },
                { "header", n => { Header = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "last_post_at", n => { LastPostAt = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "purpose", n => { Purpose = n.GetStringValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "total_msg_count", n => { TotalMsgCount = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "update_at", n => { UpdateAt = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("create_at", CreateAt);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteLongValue("delete_at", DeleteAt);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteLongValue("extra_update_at", ExtraUpdateAt);
            writer.WriteStringValue("header", Header);
            writer.WriteStringValue("id", Id);
            writer.WriteLongValue("last_post_at", LastPostAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("purpose", Purpose);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteIntValue("total_msg_count", TotalMsgCount);
            writer.WriteStringValue("type", Type);
            writer.WriteLongValue("update_at", UpdateAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
