// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChecklistItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The identifier of the user that has been assigned to complete this item. If the item has no assignee, this is an empty string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssigneeId { get; set; }
#nullable restore
#else
        public string AssigneeId { get; set; }
#endif
        /// <summary>The timestamp for the latest modification of the item&apos;s assignee, formatted as the number of milliseconds since the Unix epoch. It equals 0 if the item never got an assignee.</summary>
        public long? AssigneeModified { get; set; }
        /// <summary>The slash command associated with this item. If the item has no slash command associated, this is an empty string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>The timestamp for the latest execution of the item&apos;s command, formatted as the number of milliseconds since the Unix epoch. It equals 0 if the command was never executed.</summary>
        public long? CommandLastRun { get; set; }
        /// <summary>A detailed description of the checklist item, formatted with Markdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A unique, 26 characters long, alphanumeric identifier for the checklist item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The state of the checklist item. An empty string means that the item is not done.</summary>
        public global::Mattermost.Client.Models.ChecklistItem_state? State { get; set; }
        /// <summary>The timestamp for the latest modification of the item&apos;s state, formatted as the number of milliseconds since the Unix epoch. It equals 0 if the item was never modified.</summary>
        public long? StateModified { get; set; }
        /// <summary>The title of the checklist item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.ChecklistItem"/> and sets the default values.
        /// </summary>
        public ChecklistItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.ChecklistItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.ChecklistItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.ChecklistItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee_id", n => { AssigneeId = n.GetStringValue(); } },
                { "assignee_modified", n => { AssigneeModified = n.GetLongValue(); } },
                { "command", n => { Command = n.GetStringValue(); } },
                { "command_last_run", n => { CommandLastRun = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Mattermost.Client.Models.ChecklistItem_state>(); } },
                { "state_modified", n => { StateModified = n.GetLongValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignee_id", AssigneeId);
            writer.WriteLongValue("assignee_modified", AssigneeModified);
            writer.WriteStringValue("command", Command);
            writer.WriteLongValue("command_last_run", CommandLastRun);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Mattermost.Client.Models.ChecklistItem_state>("state", State);
            writer.WriteLongValue("state_modified", StateModified);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
