// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Command : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Use auto complete for this command</summary>
        public bool? AutoComplete { get; set; }
        /// <summary>The description for this command shown when selecting the command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoCompleteDesc { get; set; }
#nullable restore
#else
        public string AutoCompleteDesc { get; set; }
#endif
        /// <summary>The hint for this command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoCompleteHint { get; set; }
#nullable restore
#else
        public string AutoCompleteHint { get; set; }
#endif
        /// <summary>The time in milliseconds the command was created</summary>
        public int? CreateAt { get; set; }
        /// <summary>The user id for the commands creator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The time in milliseconds the command was deleted, 0 if never deleted</summary>
        public long? DeleteAt { get; set; }
        /// <summary>Description for this command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Display name for the command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The url to find the icon for this users avatar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IconUrl { get; set; }
#nullable restore
#else
        public string IconUrl { get; set; }
#endif
        /// <summary>The ID of the slash command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Is the trigger done with HTTP Get (&apos;G&apos;) or HTTP Post (&apos;P&apos;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Method { get; set; }
#nullable restore
#else
        public string Method { get; set; }
#endif
        /// <summary>The team id for which this command is configured</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The token which is used to verify the source of the payload</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>The string that triggers this command</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Trigger { get; set; }
#nullable restore
#else
        public string Trigger { get; set; }
#endif
        /// <summary>The time in milliseconds the command was last updated</summary>
        public long? UpdateAt { get; set; }
        /// <summary>The URL that is triggered</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>What is the username for the response post</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.Command"/> and sets the default values.
        /// </summary>
        public Command()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Command"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.Command CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.Command();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_complete", n => { AutoComplete = n.GetBoolValue(); } },
                { "auto_complete_desc", n => { AutoCompleteDesc = n.GetStringValue(); } },
                { "auto_complete_hint", n => { AutoCompleteHint = n.GetStringValue(); } },
                { "create_at", n => { CreateAt = n.GetIntValue(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "delete_at", n => { DeleteAt = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "icon_url", n => { IconUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "method", n => { Method = n.GetStringValue(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "trigger", n => { Trigger = n.GetStringValue(); } },
                { "update_at", n => { UpdateAt = n.GetLongValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_complete", AutoComplete);
            writer.WriteStringValue("auto_complete_desc", AutoCompleteDesc);
            writer.WriteStringValue("auto_complete_hint", AutoCompleteHint);
            writer.WriteIntValue("create_at", CreateAt);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteLongValue("delete_at", DeleteAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("icon_url", IconUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("method", Method);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("token", Token);
            writer.WriteStringValue("trigger", Trigger);
            writer.WriteLongValue("update_at", UpdateAt);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
