// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvironmentConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The AnalyticsSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_AnalyticsSettings? AnalyticsSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_AnalyticsSettings AnalyticsSettings { get; set; }
#endif
        /// <summary>The ClusterSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_ClusterSettings? ClusterSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_ClusterSettings ClusterSettings { get; set; }
#endif
        /// <summary>The ComplianceSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_ComplianceSettings? ComplianceSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_ComplianceSettings ComplianceSettings { get; set; }
#endif
        /// <summary>The EmailSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_EmailSettings? EmailSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_EmailSettings EmailSettings { get; set; }
#endif
        /// <summary>The FileSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_FileSettings? FileSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_FileSettings FileSettings { get; set; }
#endif
        /// <summary>The GitLabSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_GitLabSettings? GitLabSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_GitLabSettings GitLabSettings { get; set; }
#endif
        /// <summary>The GoogleSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_GoogleSettings? GoogleSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_GoogleSettings GoogleSettings { get; set; }
#endif
        /// <summary>The LdapSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_LdapSettings? LdapSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_LdapSettings LdapSettings { get; set; }
#endif
        /// <summary>The LocalizationSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_LocalizationSettings? LocalizationSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_LocalizationSettings LocalizationSettings { get; set; }
#endif
        /// <summary>The LogSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_LogSettings? LogSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_LogSettings LogSettings { get; set; }
#endif
        /// <summary>The MetricsSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_MetricsSettings? MetricsSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_MetricsSettings MetricsSettings { get; set; }
#endif
        /// <summary>The NativeAppSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_NativeAppSettings? NativeAppSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_NativeAppSettings NativeAppSettings { get; set; }
#endif
        /// <summary>The Office365Settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_Office365Settings? Office365Settings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_Office365Settings Office365Settings { get; set; }
#endif
        /// <summary>The PasswordSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_PasswordSettings? PasswordSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_PasswordSettings PasswordSettings { get; set; }
#endif
        /// <summary>The PrivacySettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_PrivacySettings? PrivacySettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_PrivacySettings PrivacySettings { get; set; }
#endif
        /// <summary>The RateLimitSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_RateLimitSettings? RateLimitSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_RateLimitSettings RateLimitSettings { get; set; }
#endif
        /// <summary>The SamlSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_SamlSettings? SamlSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_SamlSettings SamlSettings { get; set; }
#endif
        /// <summary>The ServiceSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_ServiceSettings? ServiceSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_ServiceSettings ServiceSettings { get; set; }
#endif
        /// <summary>The SqlSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_SqlSettings? SqlSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_SqlSettings SqlSettings { get; set; }
#endif
        /// <summary>The SupportSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_SupportSettings? SupportSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_SupportSettings SupportSettings { get; set; }
#endif
        /// <summary>The TeamSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Mattermost.Client.Models.EnvironmentConfig_TeamSettings? TeamSettings { get; set; }
#nullable restore
#else
        public global::Mattermost.Client.Models.EnvironmentConfig_TeamSettings TeamSettings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.EnvironmentConfig"/> and sets the default values.
        /// </summary>
        public EnvironmentConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.EnvironmentConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.EnvironmentConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.EnvironmentConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AnalyticsSettings", n => { AnalyticsSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_AnalyticsSettings>(global::Mattermost.Client.Models.EnvironmentConfig_AnalyticsSettings.CreateFromDiscriminatorValue); } },
                { "ClusterSettings", n => { ClusterSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ClusterSettings>(global::Mattermost.Client.Models.EnvironmentConfig_ClusterSettings.CreateFromDiscriminatorValue); } },
                { "ComplianceSettings", n => { ComplianceSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ComplianceSettings>(global::Mattermost.Client.Models.EnvironmentConfig_ComplianceSettings.CreateFromDiscriminatorValue); } },
                { "EmailSettings", n => { EmailSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_EmailSettings>(global::Mattermost.Client.Models.EnvironmentConfig_EmailSettings.CreateFromDiscriminatorValue); } },
                { "FileSettings", n => { FileSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_FileSettings>(global::Mattermost.Client.Models.EnvironmentConfig_FileSettings.CreateFromDiscriminatorValue); } },
                { "GitLabSettings", n => { GitLabSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_GitLabSettings>(global::Mattermost.Client.Models.EnvironmentConfig_GitLabSettings.CreateFromDiscriminatorValue); } },
                { "GoogleSettings", n => { GoogleSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_GoogleSettings>(global::Mattermost.Client.Models.EnvironmentConfig_GoogleSettings.CreateFromDiscriminatorValue); } },
                { "LdapSettings", n => { LdapSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LdapSettings>(global::Mattermost.Client.Models.EnvironmentConfig_LdapSettings.CreateFromDiscriminatorValue); } },
                { "LocalizationSettings", n => { LocalizationSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LocalizationSettings>(global::Mattermost.Client.Models.EnvironmentConfig_LocalizationSettings.CreateFromDiscriminatorValue); } },
                { "LogSettings", n => { LogSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LogSettings>(global::Mattermost.Client.Models.EnvironmentConfig_LogSettings.CreateFromDiscriminatorValue); } },
                { "MetricsSettings", n => { MetricsSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_MetricsSettings>(global::Mattermost.Client.Models.EnvironmentConfig_MetricsSettings.CreateFromDiscriminatorValue); } },
                { "NativeAppSettings", n => { NativeAppSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_NativeAppSettings>(global::Mattermost.Client.Models.EnvironmentConfig_NativeAppSettings.CreateFromDiscriminatorValue); } },
                { "Office365Settings", n => { Office365Settings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_Office365Settings>(global::Mattermost.Client.Models.EnvironmentConfig_Office365Settings.CreateFromDiscriminatorValue); } },
                { "PasswordSettings", n => { PasswordSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_PasswordSettings>(global::Mattermost.Client.Models.EnvironmentConfig_PasswordSettings.CreateFromDiscriminatorValue); } },
                { "PrivacySettings", n => { PrivacySettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_PrivacySettings>(global::Mattermost.Client.Models.EnvironmentConfig_PrivacySettings.CreateFromDiscriminatorValue); } },
                { "RateLimitSettings", n => { RateLimitSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_RateLimitSettings>(global::Mattermost.Client.Models.EnvironmentConfig_RateLimitSettings.CreateFromDiscriminatorValue); } },
                { "SamlSettings", n => { SamlSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SamlSettings>(global::Mattermost.Client.Models.EnvironmentConfig_SamlSettings.CreateFromDiscriminatorValue); } },
                { "ServiceSettings", n => { ServiceSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ServiceSettings>(global::Mattermost.Client.Models.EnvironmentConfig_ServiceSettings.CreateFromDiscriminatorValue); } },
                { "SqlSettings", n => { SqlSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SqlSettings>(global::Mattermost.Client.Models.EnvironmentConfig_SqlSettings.CreateFromDiscriminatorValue); } },
                { "SupportSettings", n => { SupportSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SupportSettings>(global::Mattermost.Client.Models.EnvironmentConfig_SupportSettings.CreateFromDiscriminatorValue); } },
                { "TeamSettings", n => { TeamSettings = n.GetObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_TeamSettings>(global::Mattermost.Client.Models.EnvironmentConfig_TeamSettings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_AnalyticsSettings>("AnalyticsSettings", AnalyticsSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ClusterSettings>("ClusterSettings", ClusterSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ComplianceSettings>("ComplianceSettings", ComplianceSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_EmailSettings>("EmailSettings", EmailSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_FileSettings>("FileSettings", FileSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_GitLabSettings>("GitLabSettings", GitLabSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_GoogleSettings>("GoogleSettings", GoogleSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LdapSettings>("LdapSettings", LdapSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LocalizationSettings>("LocalizationSettings", LocalizationSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_LogSettings>("LogSettings", LogSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_MetricsSettings>("MetricsSettings", MetricsSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_NativeAppSettings>("NativeAppSettings", NativeAppSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_Office365Settings>("Office365Settings", Office365Settings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_PasswordSettings>("PasswordSettings", PasswordSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_PrivacySettings>("PrivacySettings", PrivacySettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_RateLimitSettings>("RateLimitSettings", RateLimitSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SamlSettings>("SamlSettings", SamlSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_ServiceSettings>("ServiceSettings", ServiceSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SqlSettings>("SqlSettings", SqlSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_SupportSettings>("SupportSettings", SupportSettings);
            writer.WriteObjectValue<global::Mattermost.Client.Models.EnvironmentConfig_TeamSettings>("TeamSettings", TeamSettings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
