// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Invoice : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The create_at property</summary>
        public long? CreateAt { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The item property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Mattermost.Client.Models.InvoiceLineItem>? Item { get; set; }
#nullable restore
#else
        public List<global::Mattermost.Client.Models.InvoiceLineItem> Item { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The period_end property</summary>
        public long? PeriodEnd { get; set; }
        /// <summary>The period_start property</summary>
        public long? PeriodStart { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The subscription_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionId { get; set; }
#nullable restore
#else
        public string SubscriptionId { get; set; }
#endif
        /// <summary>The tax property</summary>
        public long? Tax { get; set; }
        /// <summary>The total property</summary>
        public long? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.Invoice"/> and sets the default values.
        /// </summary>
        public Invoice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Invoice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.Invoice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.Invoice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "create_at", n => { CreateAt = n.GetLongValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "item", n => { Item = n.GetCollectionOfObjectValues<global::Mattermost.Client.Models.InvoiceLineItem>(global::Mattermost.Client.Models.InvoiceLineItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "period_end", n => { PeriodEnd = n.GetLongValue(); } },
                { "period_start", n => { PeriodStart = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "subscription_id", n => { SubscriptionId = n.GetStringValue(); } },
                { "tax", n => { Tax = n.GetLongValue(); } },
                { "total", n => { Total = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("create_at", CreateAt);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Mattermost.Client.Models.InvoiceLineItem>("item", Item);
            writer.WriteStringValue("number", Number);
            writer.WriteLongValue("period_end", PeriodEnd);
            writer.WriteLongValue("period_start", PeriodStart);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("subscription_id", SubscriptionId);
            writer.WriteLongValue("tax", Tax);
            writer.WriteLongValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
