// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Mattermost.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LdapDiagnosticResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional error message if test failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Optional success/info message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Array of sample LDAP entries found</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Mattermost.Client.Models.LdapDiagnosticResult_sample_results>? SampleResults { get; set; }
#nullable restore
#else
        public List<global::Mattermost.Client.Models.LdapDiagnosticResult_sample_results> SampleResults { get; set; }
#endif
        /// <summary>Name/type of the diagnostic test being performed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestName { get; set; }
#nullable restore
#else
        public string TestName { get; set; }
#endif
        /// <summary>The actual test value (filter string or attribute name)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TestValue { get; set; }
#nullable restore
#else
        public string TestValue { get; set; }
#endif
        /// <summary>Number of entries found by the filter</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Models.LdapDiagnosticResult"/> and sets the default values.
        /// </summary>
        public LdapDiagnosticResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.LdapDiagnosticResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Mattermost.Client.Models.LdapDiagnosticResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Mattermost.Client.Models.LdapDiagnosticResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "sample_results", n => { SampleResults = n.GetCollectionOfObjectValues<global::Mattermost.Client.Models.LdapDiagnosticResult_sample_results>(global::Mattermost.Client.Models.LdapDiagnosticResult_sample_results.CreateFromDiscriminatorValue)?.AsList(); } },
                { "test_name", n => { TestName = n.GetStringValue(); } },
                { "test_value", n => { TestValue = n.GetStringValue(); } },
                { "total_count", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfObjectValues<global::Mattermost.Client.Models.LdapDiagnosticResult_sample_results>("sample_results", SampleResults);
            writer.WriteStringValue("test_name", TestName);
            writer.WriteStringValue("test_value", TestValue);
            writer.WriteIntValue("total_count", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
