// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.System.Support_packet
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\system\support_packet
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Support_packetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Support_packetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/system/support_packet{?basic_server_logs*,plugin_packets*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Support_packetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/system/support_packet{?basic_server_logs*,plugin_packets*}", rawUrl)
        {
        }
        /// <summary>
        /// Download a zip file which contains helpful and useful information for troubleshooting your mattermost instance.__Minimum server version: 5.32__##### PermissionsMust have any of the system console read permissions.##### LicenseRequires either a E10 or E20 license.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder.Support_packetRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder.Support_packetRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "404", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Download a zip file which contains helpful and useful information for troubleshooting your mattermost instance.__Minimum server version: 5.32__##### PermissionsMust have any of the system console read permissions.##### LicenseRequires either a E10 or E20 license.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder.Support_packetRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder.Support_packetRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Download a zip file which contains helpful and useful information for troubleshooting your mattermost instance.__Minimum server version: 5.32__##### PermissionsMust have any of the system console read permissions.##### LicenseRequires either a E10 or E20 license.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Support_packetRequestBuilderGetQueryParameters 
        {
            /// <summary>Specifies whether the server should include or exclude log files. Default value is true.__Minimum server version__: 9.8.0</summary>
            [QueryParameter("basic_server_logs")]
            public bool? BasicServerLogs { get; set; }
            /// <summary>Specifies plugin identifiers whose content should be included in the Support Packet.__Minimum server version__: 9.8.0</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("plugin_packets")]
            public string? PluginPackets { get; set; }
#nullable restore
#else
            [QueryParameter("plugin_packets")]
            public string PluginPackets { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Support_packetRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.System.Support_packet.Support_packetRequestBuilder.Support_packetRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
