// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Posts.Item.Actions;
using Mattermost.Client.Api.V4.Posts.Item.Files;
using Mattermost.Client.Api.V4.Posts.Item.Move;
using Mattermost.Client.Api.V4.Posts.Item.Patch;
using Mattermost.Client.Api.V4.Posts.Item.Pin;
using Mattermost.Client.Api.V4.Posts.Item.Reactions;
using Mattermost.Client.Api.V4.Posts.Item.Restore;
using Mattermost.Client.Api.V4.Posts.Item.ThreadNamespace;
using Mattermost.Client.Api.V4.Posts.Item.Unpin;
using Mattermost.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Mattermost.Client.Api.V4.Posts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\posts\{post_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPost_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Files.FilesRequestBuilder Files
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The move property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Move.MoveRequestBuilder Move
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Move.MoveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The patchPath property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Patch.PatchRequestBuilder PatchPath
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Patch.PatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pin property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Pin.PinRequestBuilder Pin
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Pin.PinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reactions property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Reactions.ReactionsRequestBuilder Reactions
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Reactions.ReactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Restore.RestoreRequestBuilder Restore
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The thread property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.ThreadNamespace.ThreadRequestBuilder Thread
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.ThreadNamespace.ThreadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unpin property</summary>
        public global::Mattermost.Client.Api.V4.Posts.Item.Unpin.UnpinRequestBuilder Unpin
        {
            get => new global::Mattermost.Client.Api.V4.Posts.Item.Unpin.UnpinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPost_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/posts/{post_id}{?include_deleted*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPost_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/posts/{post_id}{?include_deleted*}", rawUrl)
        {
        }
        /// <summary>
        /// Soft deletes a post, by marking the post as deleted in the database. Soft deleted posts will not be returned in post queries.##### PermissionsMust be logged in as the user or have `delete_others_posts` permission.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.StatusOK"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.StatusOK?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.StatusOK> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.StatusOK>(requestInfo, global::Mattermost.Client.Models.StatusOK.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a single post.##### PermissionsMust have `read_channel` permission for the channel the post is in or if the channel is public, have the `read_public_channels` permission for the team.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Post"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.Post?> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder.WithPost_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.Post> GetAsync(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder.WithPost_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.Post>(requestInfo, global::Mattermost.Client.Models.Post.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a post. Only the fields listed below are updatable, omitted fields will be treated as blank.##### PermissionsMust have `edit_post` permission for the channel the post is in.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Models.Post"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 400 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 401 status code</exception>
        /// <exception cref="global::Mattermost.Client.Models.AppError">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Mattermost.Client.Models.Post?> PutAsync(global::Mattermost.Client.Api.V4.Posts.Item.WithPost_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Mattermost.Client.Models.Post> PutAsync(global::Mattermost.Client.Api.V4.Posts.Item.WithPost_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "401", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
                { "403", global::Mattermost.Client.Models.AppError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Mattermost.Client.Models.Post>(requestInfo, global::Mattermost.Client.Models.Post.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Soft deletes a post, by marking the post as deleted in the database. Soft deleted posts will not be returned in post queries.##### PermissionsMust be logged in as the user or have `delete_others_posts` permission.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get a single post.##### PermissionsMust have `read_channel` permission for the channel the post is in or if the channel is public, have the `read_public_channels` permission for the team.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder.WithPost_ItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder.WithPost_ItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a post. Only the fields listed below are updatable, omitted fields will be treated as blank.##### PermissionsMust have `edit_post` permission for the channel the post is in.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Mattermost.Client.Api.V4.Posts.Item.WithPost_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Mattermost.Client.Api.V4.Posts.Item.WithPost_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPost_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Get a single post.##### PermissionsMust have `read_channel` permission for the channel the post is in or if the channel is public, have the `read_public_channels` permission for the team.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPost_ItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Defines if result should include deleted posts, must have &apos;manage_system&apos; (admin) permission.</summary>
            [QueryParameter("include_deleted")]
            public bool? IncludeDeleted { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPost_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Mattermost.Client.Api.V4.Posts.Item.WithPost_ItemRequestBuilder.WithPost_ItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPost_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
