// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Usage.Posts;
using Mattermost.Client.Api.V4.Usage.Storage;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Usage
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\usage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The posts property</summary>
        public global::Mattermost.Client.Api.V4.Usage.Posts.PostsRequestBuilder Posts
        {
            get => new global::Mattermost.Client.Api.V4.Usage.Posts.PostsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storage property</summary>
        public global::Mattermost.Client.Api.V4.Usage.Storage.StorageRequestBuilder Storage
        {
            get => new global::Mattermost.Client.Api.V4.Usage.Storage.StorageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Usage.UsageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/usage", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Usage.UsageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/usage", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
