// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Saml.Certificate;
using Mattermost.Client.Api.V4.Saml.Metadata;
using Mattermost.Client.Api.V4.Saml.Metadatafromidp;
using Mattermost.Client.Api.V4.Saml.Reset_auth_data;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Saml
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\saml
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SamlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The certificate property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Certificate.CertificateRequestBuilder Certificate
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Certificate.CertificateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadatafromidp property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Metadatafromidp.MetadatafromidpRequestBuilder Metadatafromidp
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Metadatafromidp.MetadatafromidpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset_auth_data property</summary>
        public global::Mattermost.Client.Api.V4.Saml.Reset_auth_data.Reset_auth_dataRequestBuilder Reset_auth_data
        {
            get => new global::Mattermost.Client.Api.V4.Saml.Reset_auth_data.Reset_auth_dataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Saml.SamlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SamlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/saml", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Saml.SamlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SamlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/saml", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
