// <auto-generated/>
#pragma warning disable CS0618
using Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v4\users\{user_id}\posts\{post_id}\reactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Mattermost.Client.api.v4.users.item.posts.item.reactions.item collection</summary>
        /// <param name="position">emoji name</param>
        /// <returns>A <see cref="global::Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.Item.WithEmoji_nameItemRequestBuilder"/></returns>
        public global::Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.Item.WithEmoji_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("emoji_name", position);
                return new global::Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.Item.WithEmoji_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.ReactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/posts/{post_id}/reactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Mattermost.Client.Api.V4.Users.Item.Posts.Item.Reactions.ReactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v4/users/{user_id}/posts/{post_id}/reactions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
